# .github/workflows/checkCLA.yml
# This workflow checks whether a user signed DLR's Individual Contributor License Agreement (CLA).
#
# There exists a list of contributors which already signed DLR's CLA called CLA_SIGNED.
# It is saved in GitHub/repo -> Settings -> Secrets and variables -> Actions -> Repository secrets.
# The list has format like: alice,bob,dev-team,janedoe
#
# The check compares the contributor's name from checked PR to the contributors listed in CLA_SIGNED.

name: "Check DLR's individual CLA"
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  contributor-signed-cla:
    runs-on: ubuntu-latest
    outputs:
      add_label: ${{ steps.check_cla_signed.outputs.add_label }}
    permissions:
      pull-requests: write
    steps:
      - name: Check if user signed CLA
        id: check_cla_signed
        run: |
          # User/contributor of PR
          USER_LOGIN="${{ github.event.pull_request.user.login }}"

          # List of users which signed CLA
          CLA_SIGNED_LIST="${{ secrets.CLA_SIGNED }}"
          IFS=',' read -ra CONTRIBUTORS <<< "$CLA_SIGNED_LIST"  # Convert list to an array

          # Check if user in list of signed CLA
          SKIP_CLA=false
          for USER in "${CONTRIBUTORS[@]}"; do
            if [[ "$USER" == "$USER_LOGIN" ]]; then
              SKIP_CLA=true
              break
            fi
          done

          if [ "$SKIP_CLA" = true ]; then
            echo "add_label=false" >> $GITHUB_OUTPUT
            echo "User $USER_LOGIN already in the list of signees of DLR's individual CLA."
          else
            echo "add_label=true" >> $GITHUB_OUTPUT
            echo "User $USER_LOGIN did not sign DLR's individual CLA yet."
            echo "Please read CONTRIBUTING.md, sign the CLA and proceed as described."
            echo ""
            echo "List of contributors who signed CLA: ${CONTRIBUTORS[*]}"
          exit 1
          fi

      - name: Add CLA label to PR or remove existing
        if: always()  # Always do this step, independent of the return of the previous step
        uses: actions/github-script@v9
        with:
          script: |
            const labelName = "CLA::not signed";  // This label must exist in the github's repo
            const issueNumber = context.payload.pull_request.number;
            const add_label = `${{ steps.check_cla_signed.outputs.add_label }}` === 'true';

            // Fetch current labels on the PR
            const labesOnPR = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });

            // Check if labelName already set in PR
            const labelExists = labesOnPR.data.some(label => label.name === labelName);

            if (add_label) {
              // Add label if it doesn't exist
              if (!labelExists) {
                await github.rest.issues.addLabels({
                  issue_number: issueNumber,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  labels: [labelName]
                });
                console.log(`Label '${labelName}' added to PR #${issueNumber}`);
              } else {
                console.log(`Label '${labelName}' already exists in PR #${issueNumber}`);
              }
            } else {
              // Remove label if it exists
              if (labelExists) {
                await github.rest.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                  name: labelName
                });
                console.log(`Label '${labelName}' removed from PR #${issueNumber}`);
              } else {
                // No action if label doesn't exist
                console.log(`Everything is fine - nothing to do`);
              }
            }

      - name: Comment on PR if CLA not signed
        if: steps.check_cla_signed.outputs.add_label == 'true'
        uses: actions/github-script@v9
        with:
          script: |
            const issueNumber = context.payload.pull_request.number;
            const userLogin = context.payload.pull_request.user.login;
            github.event.pull_request.user.login
            const repoName = context.repo.repo;
            const owner = context.repo.owner;

            const commentBody = `Thank you for your contribution to this repository!`
#             const commentBody = `@${userLogin} Thank you for your contribution to this repository!
#
# Before we can review and merge your pull request, we need you to sign **DLR's individual Contributor License Agreement (CLA)**. This is a one-time requirement for all contributors.
#
# **Please follow [CONTRIBUTING.md](https://github.com/${owner}/${repoName}/blob/main/CONTRIBUTING.md) for detailed instructions.**
#
# Your pull request will remain open and can be updated once the CLA is signed. If you have any questions about the CLA process, feel free to ask!
#
# Thank you for your understanding and cooperation.
#
# Best regards,
# The ${repoName} team`;
#
#             // // Check if comment already exists
#             // const { data: comments } = await github.rest.issues.listComments({
#             //   owner: context.repo.owner,
#             //   repo: context.repo.repo,
#             //   issue_number: issueNumber
#             // });
#             //
#             // const commentExists = comments.some(comment =>
#             //   comment.body.includes("Contributor License Agreement (CLA)") &&
#             //   comment.user.login === 'github-actions[bot]'
#             // );
#             //
#             // if (!commentExists) {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: commentBody
            });
#             //   console.log(`Comment added to PR #${issueNumber}`);
#             // } else {
#             //   console.log(`Comment already exists in PR #${issueNumber}`);
#             // }